defmodule ElixirSense.Core.ExCkReader do
  @moduledoc """
  Reads and caches ExCk chunks (Elixir checker signatures) from BEAM files.

  Signatures are cached per-module with a configurable TTL (defaults to 5 minutes).
  Returned signatures follow the layout generated by the Elixir compiler, where
  each entry is keyed by `{function, arity}` and the value is the map stored in
  the ExCk chunk (containing at least `:sig`).

  ## Version checking

  ExCk `:sig` entries encode internal `Descr` data structures that changed
  between Elixir releases (e.g. DNF lists in 1.18 vs BDDs in 1.20). Ingesting
  a chunk compiled by a different Elixir version would silently produce wrong
  types. This module therefore checks the chunk's version tag against the
  running runtime's checker version and returns `{:error, :version_mismatch}`
  for foreign chunks.

  The running runtime's version is obtained once via `:elixir_erl.checker_version/0`
  (exported from Elixir's private Erlang module). This is an internal API and
  may change; should the function disappear in a future release, the code falls
  back to probing the version by compiling a tiny in-memory module and reading
  its ExCk chunk tag.

  ## ETS lifecycle

  The cache table is owned by a dedicated long-lived owner process started on
  demand (`ensure_owner/0`). This avoids the classic race where a named ETS
  table is owned by a transient request process and disappears when that process
  exits. The owner is a locally-registered process (`:exck_reader_ets_owner`)
  that does nothing but `Process.sleep(:infinity)` so the table stays alive for
  the duration of the VM.

  The startup race (two callers racing to start the owner) is handled inside
  the candidate process itself: each candidate first tries `Process.register/2`
  (the mutual exclusion), and only the winner creates the table. A losing
  candidate exits before ever touching ETS, so the table can never be owned by
  an unregistered process.

  All ETS operations are wrapped in try/rescue with a single re-ensure+retry so
  that any transient `badarg` / `ArgumentError` (table deleted between the
  ensure and the operation, a race on table creation) is recovered from at most
  once per call.
  """

  require Logger

  @type signature_map :: %{optional({atom(), non_neg_integer()}) => map()}

  @table __MODULE__
  @chunk_id ~c"ExCk"
  @chunk_id_bin "ExCk"
  @owner_name :exck_reader_ets_owner

  @doc """
  Read ExCk signatures for `module`. Results are cached.

  Returns `{:ok, signature_map}` when a chunk exists, or `{:error, reason}` when
  no ExCk chunk is available or decoding fails.
  """
  @spec read_chunk(module(), keyword()) :: {:ok, signature_map()} | {:error, term()}
  def read_chunk(module, opts \\ []) when is_atom(module) do
    chunk_override = Keyword.get(opts, :chunk)
    cache? = chunk_override == nil and Keyword.get(opts, :cache, true)

    if cache? do
      case cache_lookup(module) do
        {:hit, cached} ->
          cached

        miss when miss in [:miss, :stale] ->
          result = do_read_chunk(module, chunk_override)
          cache_store(module, result)
      end
    else
      do_read_chunk(module, chunk_override)
    end
  end

  @doc """
  Look up the ExCk signature for `mfa`.

  Returns `{:ok, info}` with the stored map or `:error` if not found/available.
  """
  @spec lookup_signature(module(), atom(), non_neg_integer()) :: {:ok, map()} | :error
  def lookup_signature(module, function, arity) do
    case read_chunk(module) do
      {:ok, signatures} ->
        case Map.get(signatures, {function, arity}) do
          nil -> :error
          info -> {:ok, info}
        end

      {:error, _} ->
        :error
    end
  end

  # --- Internal -----------------------------------------------------------------

  defp do_read_chunk(module, chunk_override) do
    with {:ok, chunk} <- fetch_chunk(module, chunk_override),
         {:ok, signatures} <- decode_chunk(chunk) do
      {:ok, signatures}
    else
      {:error, _} = error -> error
    end
  end

  defp fetch_chunk(_module, chunk) when is_binary(chunk), do: {:ok, chunk}

  defp fetch_chunk(module, _override) do
    case fetch_from_path(module) do
      {:ok, chunk} -> {:ok, chunk}
      {:error, _} -> fetch_from_binary(module)
    end
  end

  defp fetch_from_path(module) do
    case :code.which(module) do
      path when is_list(path) ->
        # `:beam_lib.chunks/2` returns a `{:error, :beam_lib, reason}` 3-tuple.
        case :beam_lib.chunks(path, [@chunk_id]) do
          {:ok, {_path, [{@chunk_id, chunk}]}} ->
            {:ok, chunk}

          {:ok, {_path, []}} ->
            {:error, :not_found}

          {:error, :beam_lib, _reason} ->
            {:error, :not_found}
        end

      _ ->
        {:error, :not_found}
    end
  end

  defp fetch_from_binary(module) do
    case :code.get_object_code(module) do
      {^module, beam, _file} ->
        fetch_from_beam_binary(beam)

      :error ->
        {:error, :beam_not_found}
    end
  end

  defp fetch_from_beam_binary(beam) do
    # `beam` is the BEAM binary; `:beam_lib.chunks/2` returns a
    # `{:error, :beam_lib, reason}` 3-tuple.
    case :beam_lib.chunks(beam, [@chunk_id]) do
      {:ok, {_mod, [{@chunk_id, chunk}]}} -> {:ok, chunk}
      {:ok, {_mod, []}} -> extract_chunk_from_binary(beam)
      {:error, :beam_lib, _reason} -> extract_chunk_from_binary(beam)
    end
  rescue
    e ->
      Logger.debug("beam_lib.chunks failed: #{Exception.message(e)}")
      extract_chunk_from_binary(beam)
  end

  defp extract_chunk_from_binary(beam) when is_binary(beam) do
    case beam do
      <<"FOR1", _size::unsigned-big-32, "BEAM", rest::binary>> ->
        scan_chunks(rest)

      _ ->
        {:error, :invalid_beam}
    end
  end

  defp scan_chunks(<<>>), do: {:error, :not_found}

  defp scan_chunks(
         <<id::binary-size(4), size::unsigned-big-32, chunk::binary-size(size), rest::binary>>
       ) do
    # IFF (BEAM) chunks are 4-byte aligned: each chunk's data is followed by
    # zero-padding to align the next chunk header to a 4-byte boundary.
    padding = rem(4 - rem(size, 4), 4)

    if byte_size(rest) < padding do
      {:error, :invalid_beam}
    else
      <<_pad::binary-size(^padding), tail::binary>> = rest

      if id == @chunk_id_bin do
        {:ok, chunk}
      else
        scan_chunks(tail)
      end
    end
  end

  defp scan_chunks(_), do: {:error, :invalid_beam}

  defp decode_chunk(binary) do
    with {:ok, term} <- safe_binary_to_term(binary) do
      extract_signatures(term)
    end
  end

  defp safe_binary_to_term(binary) do
    {:ok, :erlang.binary_to_term(binary)}
  rescue
    e ->
      Logger.debug("binary_to_term failed: #{Exception.message(e)}")
      {:error, :invalid_chunk}
  end

  # --- Version checking ---------------------------------------------------------

  # Cache the detected checker version in `:persistent_term` so detection runs
  # once per VM lifetime, independent of the ETS table.
  @persistent_term_key {__MODULE__, :checker_version}

  @doc """
  Returns the running runtime's ExCk checker version tag (e.g.
  `:elixir_checker_v2`), or `nil` if it cannot be determined.

  Detected once and memoized in `:persistent_term`. Prefers
  `:elixir_erl.checker_version/0` when exported (older Elixir, e.g. 1.18, does
  not export it), otherwise probes by compiling a tiny module and reading its
  ExCk tag. Exposed so callers/tests can build version-matching chunks without
  depending on the private `:elixir_erl` API directly.
  """
  @spec runtime_checker_version() :: atom() | nil
  def runtime_checker_version do
    case :persistent_term.get(@persistent_term_key, :not_set) do
      :not_set ->
        version = detect_checker_version()
        # Racing writers both store the same value, so the race is harmless.
        :persistent_term.put(@persistent_term_key, version)
        version

      version ->
        version
    end
  end

  @spec detect_checker_version() :: atom() | nil
  defp detect_checker_version do
    # `:elixir_erl.checker_version/0` is an internal API that does not exist
    # before ~1.19; a literal call would emit an undefined-function warning on
    # 1.16/1.17/1.18. Dispatch via `apply/3` so it resolves at runtime only when
    # exported; otherwise fall back to compiling a probe module.
    if :erlang.function_exported(:elixir_erl, :checker_version, 0) do
      # credo:disable-for-next-line Credo.Check.Refactor.Apply
      apply(:elixir_erl, :checker_version, [])
    else
      probe_checker_version()
    end
  end

  # Fallback: compile a minimal module and extract its ExCk tag.
  # `defmodule Foo` defines `Elixir.Foo`, not the bare `:"ExCkProbe_<n>"` atom,
  # so we must NOT pin the probe atom against the compiled module name (the match
  # never succeeds); take whatever single module `Code.compile_string/1` returns.
  defp probe_checker_version do
    src = "defmodule ExCkProbe_#{:erlang.unique_integer([:positive])} do end"

    case Code.compile_string(src) do
      [{_module, beam} | _] ->
        case :beam_lib.chunks(beam, [@chunk_id]) do
          {:ok, {_, [{@chunk_id, chunk}]}} ->
            case :erlang.binary_to_term(chunk) do
              {tag, _} when is_atom(tag) -> tag
              _ -> nil
            end

          _ ->
            nil
        end

      _ ->
        nil
    end
  rescue
    _ -> nil
  end

  # ExCk `:sig` entries encode internal `Descr` data structures that differ
  # between Elixir releases. Accept only chunks produced by the same checker
  # version as the running runtime; reject others with `:version_mismatch` so
  # that callers can fall back gracefully.
  defp extract_signatures({tag, contents}) when is_atom(tag) do
    case Atom.to_string(tag) do
      "elixir_checker_v" <> _ ->
        expected = runtime_checker_version()

        if expected == nil or tag == expected do
          do_extract_signatures(contents)
        else
          {:error, :version_mismatch}
        end

      _ ->
        {:error, :invalid_payload}
    end
  end

  defp extract_signatures(_), do: {:error, :invalid_payload}

  defp do_extract_signatures(contents) when is_map(contents) do
    signatures =
      contents
      |> Map.get(:exports, [])
      |> Enum.reduce(%{}, fn
        {{fun, arity}, info}, acc when is_atom(fun) and is_integer(arity) and is_map(info) ->
          case Map.get(info, :sig) do
            nil -> acc
            sig -> Map.put(acc, {fun, arity}, %{info | sig: normalize_sig(sig)})
          end

        _, acc ->
          acc
      end)

    {:ok, signatures}
  end

  defp do_extract_signatures(_), do: {:error, :invalid_payload}

  # Normalize the ExCk `:sig` field to the 3-tuple `{kind, domain, clauses}`
  # shape the rest of ElixirSense consumes.
  #
  # Elixir 1.18 records inferred signatures as 2-tuples (`{:infer, clauses}` /
  # `{:strong, clauses}`, Module.Types types.ex) with NO domain element; 1.19/1.20
  # added a leading domain element. We canonicalize the 2-tuple form to
  # `{kind, nil, clauses}` (domain `nil` = "unknown"); `apply_signature/2`
  # tolerates a `nil` domain. This is the single boundary where 1.18 chunks are
  # made to look like 1.19/1.20 chunks, keeping downstream code version-agnostic.
  defp normalize_sig({kind, clauses}) when kind in [:infer, :strong] and is_list(clauses) do
    {kind, nil, clauses}
  end

  defp normalize_sig(sig), do: sig

  # --- Cache --------------------------------------------------------------------

  defp cache_lookup(module) do
    ensure_table()

    try do
      case :ets.lookup(@table, module) do
        [{^module, result, inserted}] ->
          if fresh?(inserted) do
            {:hit, result}
          else
            :ets.delete(@table, module)
            :stale
          end

        _ ->
          :miss
      end
    rescue
      _ ->
        # Table disappeared mid-operation; treat as a miss.
        :miss
    end
  end

  defp cache_store(module, result) do
    ensure_table()

    try do
      :ets.insert(@table, {module, result, current_time()})
    rescue
      _ ->
        # Table disappeared between ensure and insert; not fatal.
        :ok
    end

    result
  end

  defp fresh?(inserted) do
    diff = current_time() - inserted
    diff <= ttl_ms()
  end

  defp current_time, do: System.monotonic_time(:millisecond)

  defp ttl_ms do
    case Application.get_env(:elixir_sense, :exck_cache_ttl) do
      ttl when is_integer(ttl) and ttl >= 0 -> ttl
      _ -> 300_000
    end
  end

  # --- ETS owner process --------------------------------------------------------

  # All ETS state is owned by a dedicated long-lived process registered under
  # `@owner_name`, so the table survives individual request process deaths.
  #
  # Startup race: concurrent callers may both spawn an owner candidate. Each
  # candidate first tries `Process.register/2` under `@owner_name` (the mutual
  # exclusion); only the winner creates the table, so the table's owner is always
  # the registered process and killing a loser can never take the table down.

  defp ensure_table(attempts \\ 5)

  defp ensure_table(0), do: :ok

  defp ensure_table(attempts) do
    case :ets.whereis(@table) do
      :undefined ->
        ensure_owner()
        wait_for_table(20)

        if :ets.whereis(@table) == :undefined do
          # A dying owner can briefly stay name-registered while the table is
          # already gone; give the VM a beat to unregister it, then retry.
          Process.sleep(5)
          ensure_table(attempts - 1)
        else
          :ok
        end

      _tid ->
        :ok
    end
  end

  defp ensure_owner do
    case Process.whereis(@owner_name) do
      pid when is_pid(pid) ->
        # Owner running, but the public named table may have been deleted out
        # from under it. Ask the owner to (re)create it — creation must happen
        # in the owner so table ownership stays tied to the registered process.
        send(pid, :ensure_table)
        :ok

      nil ->
        start_owner()
    end
  end

  defp start_owner do
    spawn(fn ->
      try do
        Process.register(self(), @owner_name)
      rescue
        # Another candidate won the race; this spare exits without touching ETS.
        ArgumentError -> exit(:normal)
      end

      # Sole registered owner: create the table. A previous owner may be
      # mid-death with the named table not yet released — retry briefly.
      create_table(50)

      # Hold the table open until the VM stops; recreate it on demand if it was
      # deleted externally.
      owner_loop()
    end)

    :ok
  end

  defp create_table(retries) do
    # Bind the tid to silence dialyzer's unmatched_return; with :named_table the
    # table is looked up by name and the tid is unused.
    _tid = :ets.new(@table, [:named_table, :public, :set, read_concurrency: true])
    :ok
  rescue
    ArgumentError ->
      if retries > 0 and :ets.whereis(@table) == :undefined do
        Process.sleep(1)
        create_table(retries - 1)
      else
        :ok
      end
  end

  # The owner idles in a receive loop (instead of sleeping forever) so callers
  # can ask it to recreate the table after an external `:ets.delete/1`.
  defp owner_loop do
    receive do
      :ensure_table ->
        if :ets.whereis(@table) == :undefined, do: create_table(50)
        owner_loop()

      _other ->
        owner_loop()
    end
  end

  defp wait_for_table(0), do: :ok

  defp wait_for_table(n) do
    case :ets.whereis(@table) do
      :undefined ->
        Process.sleep(1)
        wait_for_table(n - 1)

      _ ->
        :ok
    end
  end
end
