defmodule ElixirSense.Core.ExCkReader do
  @moduledoc """
  Reads and caches ExCk chunks (Elixir checker signatures) from BEAM files.

  Signatures are cached per-module with a configurable TTL (defaults to 5 minutes).
  Returned signatures follow the layout generated by the Elixir compiler, where
  each entry is keyed by `{function, arity}` and the value is the map stored in
  the ExCk chunk (containing at least `:sig`).
  """

  require Logger

  @type signature_map :: %{optional({atom(), non_neg_integer()}) => map()}

  @table __MODULE__
  @chunk_id ~c"ExCk"
  @chunk_id_bin "ExCk"

  @doc """
  Read ExCk signatures for `module`. Results are cached.

  Returns `{:ok, signature_map}` when a chunk exists, or `{:error, reason}` when
  no ExCk chunk is available or decoding fails.
  """
  @spec read_chunk(module(), keyword()) :: {:ok, signature_map()} | {:error, term()}
  def read_chunk(module, opts \\ []) when is_atom(module) do
    chunk_override = Keyword.get(opts, :chunk)
    cache? = chunk_override == nil and Keyword.get(opts, :cache, true)

    if cache? do
      case cache_lookup(module) do
        {:hit, cached} ->
          cached

        :miss ->
          result = do_read_chunk(module, chunk_override)
          cache_store(module, result)

        :stale ->
          result = do_read_chunk(module, chunk_override)
          cache_store(module, result)
      end
    else
      do_read_chunk(module, chunk_override)
    end
  end

  @doc """
  Look up the ExCk signature for `mfa`.

  Returns `{:ok, info}` with the stored map or `:error` if not found/available.
  """
  @spec lookup_signature(module(), atom(), non_neg_integer()) :: {:ok, map()} | :error
  def lookup_signature(module, function, arity) do
    case read_chunk(module) do
      {:ok, signatures} ->
        case Map.get(signatures, {function, arity}) do
          nil -> :error
          info -> {:ok, info}
        end

      {:error, _} ->
        :error
    end
  end

  # --- Internal -----------------------------------------------------------------

  defp do_read_chunk(module, chunk_override) do
    with {:ok, chunk} <- fetch_chunk(module, chunk_override),
         {:ok, signatures} <- decode_chunk(chunk) do
      {:ok, signatures}
    else
      {:error, _} = error -> error
    end
  end

  defp fetch_chunk(_module, chunk) when is_binary(chunk), do: {:ok, chunk}

  defp fetch_chunk(module, _override) do
    with {:ok, chunk} <- fetch_from_path(module) do
      {:ok, chunk}
    else
      {:error, _} -> fetch_from_binary(module)
    end
  end

  defp fetch_from_path(module) do
    case :code.which(module) do
      path when is_list(path) ->
        # `:beam_lib.chunks/2` returns `{:error, :beam_lib, reason}` (a 3-tuple),
        # not `{:error, reason}`.
        case :beam_lib.chunks(path, [@chunk_id]) do
          {:ok, {_path, [{@chunk_id, chunk}]}} ->
            {:ok, chunk}

          {:ok, {_path, []}} ->
            {:error, :not_found}

          {:error, :beam_lib, _reason} ->
            {:error, :not_found}
        end

      _ ->
        {:error, :not_found}
    end
  end

  defp fetch_from_binary(module) do
    case :code.get_object_code(module) do
      {^module, beam, _file} ->
        fetch_from_beam_binary(beam)

      :error ->
        {:error, :beam_not_found}
    end
  end

  defp fetch_from_beam_binary(beam) do
    # `beam` is already the BEAM binary; pass it directly (not wrapped) and
    # match `:beam_lib`'s `{:error, :beam_lib, reason}` 3-tuple.
    case :beam_lib.chunks(beam, [@chunk_id]) do
      {:ok, {_mod, [{@chunk_id, chunk}]}} -> {:ok, chunk}
      {:ok, {_mod, []}} -> extract_chunk_from_binary(beam)
      {:error, :beam_lib, _reason} -> extract_chunk_from_binary(beam)
    end
  rescue
    e ->
      Logger.debug("beam_lib.chunks failed: #{Exception.message(e)}")
      extract_chunk_from_binary(beam)
  end

  defp extract_chunk_from_binary(beam) when is_binary(beam) do
    case beam do
      <<"FOR1", _size::unsigned-big-32, "BEAM", rest::binary>> ->
        scan_chunks(rest)

      _ ->
        {:error, :invalid_beam}
    end
  end

  defp scan_chunks(<<>>), do: {:error, :not_found}

  defp scan_chunks(
         <<id::binary-size(4), size::unsigned-big-32, chunk::binary-size(size), rest::binary>>
       ) do
    padding = rem(size, 2)

    if byte_size(rest) < padding do
      {:error, :invalid_beam}
    else
      <<_pad::binary-size(^padding), tail::binary>> = rest

      if id == @chunk_id_bin do
        {:ok, chunk}
      else
        scan_chunks(tail)
      end
    end
  end

  defp scan_chunks(_), do: {:error, :invalid_beam}

  defp decode_chunk(binary) do
    with {:ok, term} <- safe_binary_to_term(binary),
         {:ok, signatures} <- extract_signatures(term) do
      {:ok, signatures}
    end
  end

  defp safe_binary_to_term(binary) do
    {:ok, :erlang.binary_to_term(binary)}
  rescue
    e ->
      Logger.debug("binary_to_term failed: #{Exception.message(e)}")
      {:error, :invalid_chunk}
  end

  # The ExCk chunk is tagged with a checker version atom (elixir_checker_v1
  # through v8 and counting). The `%{exports: [...], mode: ...}` contents layout
  # — including the per-export `:sig` entry — has stayed stable across these
  # bumps, so we accept any `:elixir_checker_v*` tag rather than enumerating
  # versions that drift on every Elixir release.
  defp extract_signatures({tag, contents}) when is_atom(tag) do
    case Atom.to_string(tag) do
      "elixir_checker_v" <> _ -> do_extract_signatures(contents)
      _ -> {:error, :invalid_payload}
    end
  end

  defp extract_signatures(_), do: {:error, :invalid_payload}

  defp do_extract_signatures(contents) when is_map(contents) do
    signatures =
      contents
      |> Map.get(:exports, [])
      |> Enum.reduce(%{}, fn
        {{fun, arity}, info}, acc when is_atom(fun) and is_integer(arity) and is_map(info) ->
          case Map.get(info, :sig) do
            nil -> acc
            _ -> Map.put(acc, {fun, arity}, info)
          end

        _, acc ->
          acc
      end)

    {:ok, signatures}
  end

  defp do_extract_signatures(_), do: {:error, :invalid_payload}

  # --- Cache --------------------------------------------------------------------

  defp cache_lookup(module) do
    ensure_table()

    case :ets.lookup(@table, module) do
      [{^module, result, inserted}] ->
        if fresh?(inserted) do
          {:hit, result}
        else
          :ets.delete(@table, module)
          :stale
        end

      _ ->
        :miss
    end
  end

  defp cache_store(module, result) do
    ensure_table()
    :ets.insert(@table, {module, result, current_time()})
    result
  end

  defp fresh?(inserted) do
    diff = current_time() - inserted
    diff <= ttl_ms()
  end

  defp current_time, do: System.monotonic_time(:millisecond)

  defp ttl_ms do
    case Application.get_env(:elixir_sense, :exck_cache_ttl) do
      ttl when is_integer(ttl) and ttl >= 0 -> ttl
      _ -> 300_000
    end
  end

  defp ensure_table do
    _ =
      case :ets.info(@table) do
        :undefined -> :ets.new(@table, [:named_table, :public, :set, read_concurrency: true])
        _ -> :ok
      end

    :ok
  end
end
